"""Pin the broker's dependencies, with hashes, for one installer platform.

    python tools/lock_bundle.py windows   writes packaging/requirements-windows.txt
    python tools/lock_bundle.py macos     writes packaging/requirements-macos-arm64.txt and -macos-x86_64.txt

Run it on the platform it locks for, with the Python version in packaging/runtimes.json, because pip evaluates
environment markers such as sys_platform for the running interpreter. The Installers workflow does that when
a lock file is missing, or when it is run with "relock", and attaches the result to the run.

It uses pip's resolver without installing anything (pip install --dry-run --report) and skips any release
younger than MIN_AGE_DAYS, so a version published moments ago never lands in an installer.
"""

import argparse
import json
import re
import subprocess
import sys
import tempfile
import tomllib
import urllib.request
from datetime import datetime, timedelta, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
RUNTIMES = json.loads((REPO / "packaging" / "runtimes.json").read_text(encoding="utf-8"))
TARGETS = {"windows": ["windows"], "macos": ["macos-arm64", "macos-x86_64"]}
MIN_AGE_DAYS = 7


def lock_path(runtime: str) -> Path:
    return REPO / "packaging" / f"requirements-{runtime}.txt"


def pip_target_args(runtime: str) -> list[str]:
    """pip options that pick wheels for a bundled runtime rather than for the running Python."""
    args = ["--only-binary=:all:", "--python-version", RUNTIMES["python"], "--implementation", "cp"]
    for platform in RUNTIMES[runtime]["pip_platforms"]:
        args += ["--platform", platform]
    return args


def canonical(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def broker_requirements() -> list[str]:
    project = tomllib.loads((REPO / "broker" / "pyproject.toml").read_text(encoding="utf-8"))["project"]
    return project["dependencies"]


def resolve(runtime: str, constraints: list[str]) -> dict[str, tuple[str, str]]:
    """{name: (version, sha256 of the chosen wheel)}"""
    with tempfile.TemporaryDirectory() as tmp:
        report, cons = Path(tmp) / "report.json", Path(tmp) / "constraints.txt"
        cons.write_text("".join(f"{c}\n" for c in constraints), encoding="utf-8")
        subprocess.run([sys.executable, "-m", "pip", "install", "--dry-run", "--ignore-installed", "--quiet",
                        "--report", str(report), "-c", str(cons), *pip_target_args(runtime),
                        *broker_requirements()], check=True)
        items = json.loads(report.read_text(encoding="utf-8"))["install"]
    picks = {}
    for item in items:
        archive = item["download_info"]["archive_info"]
        sha256 = archive.get("hashes", {}).get("sha256") or archive["hash"].removeprefix("sha256=")
        picks[canonical(item["metadata"]["name"])] = (item["metadata"]["version"], sha256)
    return picks


def first_upload(name: str, version: str) -> datetime:
    with urllib.request.urlopen(f"https://pypi.org/pypi/{name}/{version}/json", timeout=30) as resp:
        files = json.load(resp)["urls"]
    return min(datetime.fromisoformat(f["upload_time_iso_8601"].replace("Z", "+00:00")) for f in files)


def lock(runtime: str) -> dict[str, tuple[str, str]]:
    cutoff = datetime.now(timezone.utc) - timedelta(days=MIN_AGE_DAYS)
    constraints: list[str] = []
    for _ in range(25):
        picks = resolve(runtime, constraints)
        young = [f"{name}!={version}" for name, (version, _) in picks.items()
                 if first_upload(name, version) > cutoff]
        if not young:
            return picks
        print(f"{runtime}: skipping releases younger than {MIN_AGE_DAYS} days: {', '.join(young)}")
        constraints += young
    raise SystemExit("Could not find a set of releases that are all old enough.")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("os", choices=sorted(TARGETS))
    args = parser.parse_args()
    for runtime in TARGETS[args.os]:
        lines = [f"# Generated by tools/lock_bundle.py {args.os}: the broker's dependencies in the {runtime} runtime.",
                 "# Regenerate with that script rather than editing by hand."]
        for name, (version, sha256) in sorted(lock(runtime).items()):
            lines += [f"{name}=={version} \\", f"    --hash=sha256:{sha256}"]
        lock_path(runtime).write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"wrote {lock_path(runtime)}")


if __name__ == "__main__":
    main()
